line_endings = "Unix"
syntax = "Lua53"
indent_type = "Tabs"
indent_width = 2
column_width = 66
#column_width = 160
quote_style = "AutoPreferDouble"
call_parentheses = "Input"
collapse_simple_statement = "Always"

[sort_requires]
enabled = true
